name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov
    
    - name: Run smoke tests
      run: |
        python src/test_smoke.py
    
    - name: Run unit tests
      run: |
        pytest -xvs tests/
    
    - name: Generate coverage report
      run: |
        pytest --cov=src tests/
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: false 

  backtest-smoke:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run 7-day backtest
      run: |
        python src/backtest/run_backtest.py --symbols BTCUSDT --timeframe 4h --days 7
        
    - name: Run 7-day portfolio backtest
      run: |
        python src/backtest/run_backtest.py --symbols BTCUSDT ETHUSDT SOLUSDT BNBUSDT --timeframe 4h --days 7 