name: Performance Logging

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:     # Allow manual triggering

jobs:
  backtest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run baseline backtest
      run: |
        python log_performance.py --symbol BTC/USDT --days 90 --timeframe 1h --strategy ema_crossover --log --git-commit

    - name: Run RSI momentum backtest
      run: |
        python log_performance.py --symbol BTC/USDT --days 90 --timeframe 1h --strategy rsi_momentum --log --git-commit
        
    - name: Run longer-term backtest
      run: |
        python log_performance.py --symbol BTC/USDT --days 180 --timeframe 4h --strategy ema_crossover --log --git-commit
    
    - name: Push changes
      if: success()
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git push 